### ISSUE TITLE
Problems under Arch Linux

### ISSUE THREAD

**Issue by airon90** [MoonLightDE/MoonLightDE#15] opened 2014-07-07 09:35 UTC
It seems that MoonLightDE doesn't compile on Arch Linux:

here is the output of cmake: http://pastebin.com/nhaAYAth
here is the log of cmake: http://pastebin.com/4SFkD6hz

**Comment by mckaygerhard** [comment] 2017-08-20 18:52
the problem taken from log are that required libraries are not installed and fails to compile.. close it due its not a bug, but are caused due documentation dont point that.. documentation are currently updated
```
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at src/core/CMakeLists.txt:75 (find_package):
  By not providing "FindQT5XDG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QT5XDG", but
  CMake did not find one.
 
  Could not find a package configuration file provided by "QT5XDG" with any
  of the following names:
 
    QT5XDGConfig.cmake
    qt5xdg-config.cmake
 
  Add the installation prefix of "QT5XDG" to CMAKE_PREFIX_PATH or set
  "QT5XDG_DIR" to a directory containing one of the above files.  If "QT5XDG"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Closed by mckaygerhard** 2017-08-20 18:52 UTC
Labels: invalid
